function raw_data_plots()

[y,Fs] = audioread('melody_1.wav');
frIsequence = GetMusicFeatures(y,Fs);
figure(1)
plot(frIsequence(1,:))
title('melody\_1')
xlabel('Time')
ylabel('Frequency, Hz')
figure(2)
plot(frIsequence(2,:))
title('melody\_1')
xlabel('Time')
ylabel('Correlation coefficient')
figure(3)
plot(frIsequence(3,:))
title('melody\_1')
xlabel('Time')
ylabel('Root-mean-square intensity')

[y,Fs] = audioread('melody_2.wav');
frIsequence = GetMusicFeatures(y,Fs);
figure(4)
plot(frIsequence(1,:))
title('melody\_2')
xlabel('Time')
ylabel('Frequency, Hz')
figure(5)
plot(frIsequence(2,:))
title('melody\_2')
xlabel('Time')
ylabel('Correlation coefficient')
figure(6)
plot(frIsequence(3,:))
title('melody\_2')
xlabel('Time')
ylabel('Root-mean-square intensity')

[y,Fs] = audioread('melody_3.wav');
frIsequence = GetMusicFeatures(y,Fs);
figure(7)
plot(frIsequence(1,:))
title('melody\_3')
xlabel('Time')
ylabel('Frequency, Hz')
figure(8)
plot(frIsequence(2,:))
title('melody\_3')
xlabel('Time')
ylabel('Correlation coefficient')
figure(9)
plot(frIsequence(3,:))
title('melody\_3')
xlabel('Time')
ylabel('Root-mean-square intensity')

[y,Fs] = audioread('melody_4.wav');
frIsequence = GetMusicFeatures(y,Fs);
figure(10)
plot(frIsequence(1,:))
title('Own melody')
xlabel('Time')
ylabel('Frequency, Hz')
figure(11)
plot(frIsequence(2,:))
title('Own melody')
xlabel('Time')
ylabel('Correlation coefficient')
figure(12)
plot(frIsequence(3,:))
title('Own melody')
xlabel('Time')
ylabel('Root-mean-square intensity')
